site_name: Silvermilight's Knowledge Base
site_url: https://rzm0572.github.io/KnowledgeBase/
repo_url: https://github.com/rzm0572/KnowledgeBase/
repo_name: rzm0572/KnowledgeBase
site_author: Silvermilight
site_description: Silvermilight 的笔记本
copyright: Copyright &copy; 2024 Silvermilight

theme:
  name: material
  language: zh
  font: false
  icon:
    logo: material/database-outline
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tracking
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - search.highlight
    - content.code.copy
    - content.code.annotate

plugins: 
  - search
  - statistics
  - tags
  - git-revision-date-localized:
      enable_creation_date: true

extra: 
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rzm0572/

extra_css:
  - stylesheets/custom.css
  - stylesheets/extra.css
  # - sytlesheets/cards.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions: 
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
      toc_depth: 4

nav:
  - Home Page:
    - index.md
  - Computer Science:
    - cs/index.md
    # - Programming Language:
    #   - cs/programming_language/index.md
    - System:
      - cs/system/index.md
    #   - ZJU System I:
    #     - cs/system/zju_system_I/index.md
    #   - ZJU System II:
    #     - cs/system/zju_system_II/index.md
      - ZJU System III:
        - cs/system/zju_system_III/index.md
        - Ch.1 Introduction: cs/system/zju_system_III/chapter1.md
        - Ch.3 ILP: cs/system/zju_system_III/chapter3.md
    #   - NJU PA Lab:
    #     - cs/system/nju_PA_lab/index.md
    #   - CSAPP:
    #     - cs/system/CSAPP/index.md
    - HPC:
      - cs/HPC/index.md
    - Algorithm:
      - cs/algorithm/index.md
      - ADS:
        - cs/algorithm/ads/index.md
    - AI:
      - cs/AI/index.md
      - 人工智能引论:
        - cs/AI/AI_intro/index.md
    - Database Systems:
      - cs/DB/index.md
      - Ch.1 Introduction: cs/DB/chapter1.md
      - Ch.2 Relation Model: cs/DB/chapter2.md
      - Ch.3 SQL: cs/DB/chapter3.md
      - Ch.6 E-R Model: cs/DB/chapter6.md
    # - Tools:
    #   - cs/tools/index.md
  - Math & Phys:
    - math_phys/index.md
    - Analysis:
      - math_phys/analysis/index.md
    # - ODE:
    #   - math_phys/ODE/index.md
    # - General Physics I:
    #   - math_phys/general_physics_I/index.md
    # - General Physics II:
    #   - math_phys/general_physics_II/index.md
    - Numerical Analysis:
      - math_phys/numerical_analysis/index.md
      - Ch.1 Mathematical Preliminaries: math_phys/numerical_analysis/chapter1.md
      - Ch.2 Solution of Equations in One Variable: math_phys/numerical_analysis/chapter2.md
      - Ch.3 Interpolation and Polynomial Approximation: math_phys/numerical_analysis/chapter3.md
      - Ch.4 Numerical Differentiation and Integration: math_phys/numerical_analysis/chapter4.md
      - Ch.6 Direct Methods for Solving Linear Systems: math_phys/numerical_analysis/chapter6.md
      - Ch.7 Iterative Techniques in Matrix Algebra: math_phys/numerical_analysis/chapter7.md
      - Ch.8 Approximation Theory: math_phys/numerical_analysis/chapter8.md
    - Fundamentals of Quantum Information:
      - math_phys/FQI/index.md
  - Misc:
    - misc/index.md

